const FAMILY_POPULAR_NAMES: Record<string, string> = {
    "acantáceas": "acanto, justícia, ruélia, camarão-vermelho",
    "acoráceas": "cálamo-aromático, ácoro, junco-cheiroso",
    "actinidiáceas": "kiwi, quivi, kiwi-de-jardim",
    "alismatáceas": "chapéu-de-couro, alisma, erva-de-colhereiro",
    "alstroemeriáceas": "astromélia, lírio-dos-incas",
    "altingiáceas": "liquidâmbar, árvore-do-âmbar",
    "amarantáceas": "caruru, bredo, amaranto, erva-de-jacaré, tripa-de-galinha",
    "amarilidáceas": "alho, cebola, cebolinha, agapanto, açucena, narciso",
    "anonáceas": "fruta-do-conde, pinha, graviola, araticum",
    "apiáceas": "salsa, coentro, cenoura, funcho, erva-doce",
    "apocináceas": "alamanda, jasmim-manga, vinca, espirradeira",
    "aráceas": "comigo-ninguém-pode, antúrio, copo-de-leite, taioba, costela-de-adão",
    "araliáceas": "hera, cheflera, árvore-guarda-chuva",
    "araucariáceas": "araucária, pinheiro-do-paraná",
    "arecáceas": "palmeira, coqueiro, açaizeiro, palmito",
    "asfodeláceas": "babosa, aloe, asfódelo",
    "asparagáceas": "aspargo, espada-de-são-jorge, dracena, agave",
    "asteráceas": "margarida, girassol, camomila, dente-de-leão, carqueja",
    "betuláceas": "bétula, amieiro, avelã",
    "bignoniáceas": "ipê, jacarandá, sete-léguas, cipó-de-são-joão",
    "brassicáceas": "couve, repolho, mostarda, rúcula, agrião",
    "bromeliáceas": "bromélia, abacaxi, gravatá, caraguatá",
    "campanuláceas": "campânula, sininho, lobélia",
    "caprifoliáceas": "madressilva, sabugueiro, abélia",
    "celastráceas": "espinheira-santa, evônimo",
    "cercidifiláceas": "katsura, árvore-katsura",
    "cornáceas": "corniso, sangüinho",
    "crassuláceas": "suculenta, flor-da-fortuna, jade, sedum",
    "cupressáceas": "cipreste, tuia, zimbro, junípero",
    "didiereáceas": "aluaudia, árvore-ocotilho-de-madagascar",
    "ebenáceas": "caqui, caquizeiro, ébano",
    "eleagnáceas": "eleagno, espinheiro-marítimo, oliveira-do-paraíso",
    "ericáceas": "azaleia, rododendro, mirtilo, urze",
    "euforbiáceas": "mamona, coroa-de-cristo, bico-de-papagaio, mandioca",
    "fabáceas": "feijão, ervilha, soja, acácia, flamboyant, pau-brasil",
    "fagáceas": "carvalho, castanheiro, faia",
    "gesneriáceas": "violeta-africana, gloxínia, columéia",
    "ginkgoáceas": "ginkgo, árvore-avenca",
    "hamamelidáceas": "hamamélis, aveleira-de-bruxa",
    "hortensiáceas": "hortênsia",
    "juglandáceas": "nogueira, noz-pecã",
    "lamiáceas": "hortelã, manjericão, alecrim, sálvia, lavanda",
    "lardizabaláceas": "aquébia, trepadeira-chocolate",
    "lauráceas": "louro, abacateiro, canela, caneleira",
    "litráceas": "resedá, escumilha",
    "magnoliáceas": "magnólia, tulipeiro",
    "malváceas": "hibisco, malva, algodão, quiabo, baobá",
    "meliáceas": "cedro, mogno, cinamomo",
    "mirtáceas": "goiabeira, jabuticabeira, pitangueira, eucalipto",
    "moráceas": "figueira, amoreira, jaca",
    "nissáceas": "tupelo, nissa",
    "oleáceas": "oliveira, jasmim, ligustro, freixo",
    "orobancáceas": "orobanca, erva-de-bruxa, planta-parasita",
    "paulowniáceas": "paulônia, kiri",
    "pináceas": "pinheiro, abeto, pícea, cedro, lariço",
    "plumbagináceas": "bela-emília, plumbago, estatice",
    "poáceas": "capim, grama, bambu, milho, arroz, trigo",
    "podocarpáceas": "podocarpo, pinheiro-de-buda",
    "pteridáceas": "avenca, samambaia",
    "ranunculáceas": "ranúnculo, anêmona, clemátis, acônito",
    "rosáceas": "rosa, macieira, morangueiro, pessegueiro, ameixeira",
    "rubiáceas": "café, ixora, gardênia",
    "sapindáceas": "bordo, lichia, guaraná, castanheiro-da-índia",
    "simarubáceas": "pau-amargo, ailanto",
    "teáceas": "camélia, chá, chá-da-índia",
    "verbenáceas": "verbena, lantana, erva-cidreira-de-arbusto",
    "winteráceas": "casca-d'anta, cataia, pimenteira",
    "zingiberáceas": "gengibre, açafrão-da-terra, alpínia, cardamomo",
};

export function getFamilyPopularName(family?: string | null): string {
    const normalizedFamily = family?.trim().toLowerCase() ?? "";
    return FAMILY_POPULAR_NAMES[normalizedFamily] ?? family?.trim() ?? "";
}

export function getFamilyPopularNameMap(): Record<string, string> {
    return { ...FAMILY_POPULAR_NAMES };
}
